id: P255114CD
initial_creation_type: input
source_metadata:
  title: Jigme Tenpé Wangchuk Series
  language: bo
  description: 'Texts by and about the Sixth Gungthang Lama, Jigme Tenpé Wangchuk
    (''jigs med bstan pa''i dbang phyug, 1926–2000):'
  volume:
    6c19a7c5ba424bce8ba56fb3c8275481:
      title: Aspiration for Electric Lamps
      parent: Aspiration Prayers
created_at: '2022-03-01T00:08:17.082656'
last_modified_at: '2022-03-01T00:08:17.082658'
